### ISSUE TITLE
Remove the delete button

### ISSUE THREAD

**Issue by shahilg** [mwasiluk/angular-surveys#22]
Is there any way to remove the delete button which is related to the form element. I want the user not to remove the element from the form while editing it. Looking forward to the reply. 
Thanks.

**Comment by vangorra** [comment]
Wouldn't CSS be a good solution for this?

``` css
.mw-form-builder .remove-button {
  display: none;
}
```
